version: 0.2

env: 
  variables:
      NEXT_PUBLIC_USER_POOL_ID: $NEXT_PUBLIC_USER_POOL_ID
      NEXT_PUBLIC_USER_POOL_CLIENT_ID: $NEXT_PUBLIC_USER_POOL_CLIENT_ID
      NEXT_PUBLIC_AWS_REGION: $NEXT_PUBLIC_AWS_REGION
      NEXT_PUBLIC_API_URL: $NEXT_PUBLIC_API_URL

phases:
  pre_build:
    commands:
      - echo Build started on `date`
      - cd cx-agent-react
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build --verbose
  post_build:
    commands:
      - echo Build completed on `date`
      - aws s3 sync out/ s3://$S3_BUCKET --delete
      - echo Creating CloudFront invalidation...
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
